site_name: 2083-CN
site_description: 2083 — 欧洲独立宣言 中文译本
repo_url: https://github.com/linull24/2083-CN
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
plugins:
  - search:
      lang: zh
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
